import { LegalPage, LegalH2, LegalWarning } from "@/components/legal-page";

export const metadata = { title: "Terms of Use — Ruichi" };

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Use">
      <p className="text-xs text-muted">Last updated: 22 September 2026</p>

      <LegalH2>1. Introduction</LegalH2>
      <p>
        These Terms of Use (the &ldquo;Terms&rdquo;) govern your access to and use of the Ruichi
        platform available at https://ruichi.online (the &ldquo;Platform&rdquo;), operated by Ruichi
        (&ldquo;Ruichi&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo; or &ldquo;our&rdquo;). By
        registering for an account and/or accessing the Platform, you agree to be bound by these
        Terms in their entirety. If you do not accept them, you must not use the Platform.
      </p>

      <LegalH2>2. Definitions</LegalH2>
      <p>
        &ldquo;Platform&rdquo; means the Ruichi web application, together with its content, software,
        databases and updates. &ldquo;Content&rdquo; means the structure, editorial content, icons,
        illustrations, images, trademarks, logos and all other elements comprising the Platform.
        &ldquo;Services&rdquo; means the functionality made available through the Platform.
        &ldquo;User&rdquo; means a person of full legal age who has registered for an account as a
        business-introduction partner, whether as an employee or as a self-employed / freelance
        contractor. &ldquo;Data&rdquo; means any information made available to, generated by, or
        accessible through the Platform, including user data, partner data, transaction records,
        invoices, pricing, commission rules and any non-public business information.
      </p>

      <LegalH2>3. Purpose of the Platform</LegalH2>
      <p>
        Ruichi is a digital platform that connects partner maisons and boutiques with their clients
        through an efficient and private channel. The Services include, among others: creating and
        managing a personal account, uploading supporting documents, declaring invoices and purchase
        receipts, tracking their validation, and the calculation, tracking and settlement of
        cashback and commissions.
      </p>

      <LegalH2>4. Access to the Platform</LegalH2>
      <p>
        The Platform is accessible free of charge through any modern web browser. Internet access
        and a compatible device are required. Access to your personal space requires the creation of
        an account with a valid email address and a password. You are responsible for maintaining
        the confidentiality of your login credentials and for all activity conducted under your
        account.
      </p>

      <LegalH2>5. Fees</LegalH2>
      <p>
        Use of the Platform is free of charge, save for any telecommunications, internet-connection
        or data charges, which remain your responsibility.
      </p>

      <LegalH2>6. Intellectual Property</LegalH2>
      <p>
        Ruichi is the exclusive owner of, or holds the rights to use, all intellectual property
        rights in the Platform and the Content, save for content published by partners and documents
        uploaded by Users. Ruichi grants you a personal, non-exclusive, revocable, non-assignable,
        non-transferable and royalty-free licence to use the Platform, the Content and the Services
        solely for the purposes of your business-introduction activity. Access to source code and
        software components is strictly prohibited. Any reproduction, representation, adaptation or
        exploitation of the Content is prohibited without our prior written consent, and will be
        pursued in accordance with the laws of the Hong Kong Special Administrative Region.
      </p>

      <LegalH2>7. User Obligations</LegalH2>
      <p>You undertake, in particular:</p>
      <ul className="list-disc space-y-1 pl-6">
        <li>to provide accurate, truthful and up-to-date information and documents;</li>
        <li>to declare only genuine invoices and purchase receipts;</li>
        <li>not to reproduce the Platform, in whole or in part;</li>
        <li>
          not to adapt, modify, translate, decompile or reverse-engineer the Platform, nor extract
          content from its databases without authorisation;
        </li>
        <li>not to use any software that disrupts the operation of the Platform;</li>
        <li>not to hack the Platform or otherwise breach these Terms;</li>
        <li>to notify Ruichi of any act of piracy of which you become aware;</li>
        <li>not to sell, rent or otherwise distribute access to the Platform to any third party;</li>
        <li>to keep your login credentials confidential.</li>
      </ul>

      <LegalH2>8. Confidentiality of Data — Strict Prohibition on Disclosure</LegalH2>
      <LegalWarning>
        <p className="font-medium text-ink">
          STRICTLY CONFIDENTIAL. All Data accessed through or obtained from the Platform is the
          confidential property of Ruichi and/or its partners.
        </p>
        <p className="mt-2">
          You are <strong>strictly prohibited</strong> from disclosing, publishing, disseminating,
          reproducing, transferring, selling, or otherwise making available to any third party, by
          any means and in any medium, any Data accessed through or obtained from the Platform,
          including but not limited to user information, partner information, client information,
          invoices, transaction records, pricing, and commission rules, whether during or after your
          use of the Platform, without the prior written consent of Ruichi.
        </p>
        <p className="mt-2">
          <strong>
            Any breach of this clause will be pursued to the fullest extent permitted by law.
          </strong>{" "}
          Ruichi reserves the right to suspend or terminate your account immediately and to seek all
          available remedies, including injunctive relief and damages, against any person who
          discloses Data in breach of this clause. You shall indemnify Ruichi against all losses,
          liabilities, costs and expenses arising out of or in connection with any such breach.
        </p>
      </LegalWarning>
      <p>
        This confidentiality obligation is a material term of these Terms and survives the
        termination of your account for any reason.
      </p>

      <LegalH2>9. Availability of the Platform</LegalH2>
      <p>
        The Platform is accessible 24 hours a day, 7 days a week, save in cases of force majeure,
        events beyond our control, or necessary maintenance, which may be carried out without prior
        notice.
      </p>

      <LegalH2>10. Limitation of Warranty and Liability</LegalH2>
      <p>
        Access to the Platform is at your own risk. The Platform is provided &ldquo;as is&rdquo; and
        &ldquo;as available&rdquo;, without warranty of any kind. You accept the characteristics and
        limits of the internet, including network failures, saturation, transmission delays and the
        risk of interception. To the maximum extent permitted by law, Ruichi shall not be liable for
        any defect, loss, delay or error in transmission, misuse of your device, or any indirect
        damage (such as loss of business or loss of opportunity) arising from use of the Platform.
      </p>

      <LegalH2>11. Amendments</LegalH2>
      <p>
        The Terms in force at the time of each connection apply. Ruichi may amend them at any time
        and without prior notice in order to adapt to technical or legal developments or to new
        services. Amendments are deemed accepted by any User who accesses the Platform after they
        are published.
      </p>

      <LegalH2>12. Termination</LegalH2>
      <p>
        Ruichi may terminate your access to the Platform at any time, in particular in the event of
        a breach of these Terms. Upon termination, the rights and licences granted to you cease and
        you must cease all use of the Platform. Clauses which by their nature should survive
        termination, including Clause 8 (Confidentiality of Data), shall continue in effect.
      </p>

      <LegalH2>13. Governing Law and Jurisdiction</LegalH2>
      <p>
        These Terms are governed by and construed in accordance with the laws of the Hong Kong
        Special Administrative Region of the People&rsquo;s Republic of China. Any dispute arising
        out of or in connection with these Terms shall be subject to the exclusive jurisdiction of
        the courts of Hong Kong.
      </p>

      <LegalH2>14. Contact</LegalH2>
      <p>Any question regarding these Terms may be addressed to: Ruichi — contact@ruichi.online.</p>
    </LegalPage>
  );
}
